/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InviteQuotaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'maxInvites', 'resetAt', 'updatedAt', 'usedInvites', 'userId'] as const
  $columns = InviteQuotaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxInvites: number
  @column.dateTime()
  declare resetAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare usedInvites: number
  @column()
  declare userId: bigint | number
}

export class InviteSchema extends BaseModel {
  static $columns = ['accountExpiryDays', 'allowedLibraries', 'code', 'createdAt', 'createdBy', 'expiresAt', 'id', 'isActive', 'label', 'maxStreams', 'maxUses', 'remainingUses', 'updatedAt'] as const
  $columns = InviteSchema.$columns
  @column()
  declare accountExpiryDays: number | null
  @column()
  declare allowedLibraries: any | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: bigint | number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare label: string | null
  @column()
  declare maxStreams: number | null
  @column()
  declare maxUses: number | null
  @column()
  declare remainingUses: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaRequestSchema extends BaseModel {
  static $columns = ['createdAt', 'externalId', 'id', 'mediaType', 'notes', 'requestedAt', 'respondedAt', 'respondedBy', 'seasons', 'serviceInstanceId', 'status', 'title', 'tmdbId', 'updatedAt', 'userId'] as const
  $columns = MediaRequestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mediaType: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare requestedAt: DateTime
  @column.dateTime()
  declare respondedAt: DateTime | null
  @column()
  declare respondedBy: bigint | number | null
  @column()
  declare seasons: any | null
  @column()
  declare serviceInstanceId: bigint | number | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare tmdbId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'read', 'title', 'type', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare read: boolean
  @column()
  declare title: string
  @column()
  declare type: string
  @column()
  declare userId: bigint | number
}

export class ReferralSchema extends BaseModel {
  static $columns = ['accountExpiresAt', 'createdAt', 'id', 'inviteId', 'jellyfinUserId', 'notifiedExpiry', 'referredUserId', 'sponsorId', 'status'] as const
  $columns = ReferralSchema.$columns
  @column.dateTime()
  declare accountExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inviteId: bigint | number
  @column()
  declare jellyfinUserId: string
  @column()
  declare notifiedExpiry: boolean
  @column()
  declare referredUserId: bigint | number
  @column()
  declare sponsorId: bigint | number
  @column()
  declare status: string
}

export class ServiceInstanceSchema extends BaseModel {
  static $columns = ['apiKey', 'createdAt', 'id', 'isActive', 'isDefault', 'name', 'qualityProfileId', 'rootFolder', 'type', 'updatedAt', 'url'] as const
  $columns = ServiceInstanceSchema.$columns
  @column()
  declare apiKey: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare qualityProfileId: number
  @column()
  declare rootFolder: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'id', 'jellyfinId', 'jellyfinToken', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jellyfinId: string
  @column({ serializeAs: null })
  declare jellyfinToken: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class WatchHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'durationTicks', 'episodeNumber', 'id', 'jellyfinItemId', 'mediaType', 'percentPlayed', 'playedTicks', 'seasonNumber', 'seriesName', 'title', 'updatedAt', 'userId', 'watchedAt'] as const
  $columns = WatchHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationTicks: bigint | number
  @column()
  declare episodeNumber: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jellyfinItemId: string
  @column()
  declare mediaType: string
  @column()
  declare percentPlayed: number
  @column()
  declare playedTicks: bigint | number
  @column()
  declare seasonNumber: number | null
  @column()
  declare seriesName: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
  @column.dateTime()
  declare watchedAt: DateTime
}

export class WatchSessionSchema extends BaseModel {
  static $columns = ['clientName', 'createdAt', 'deviceName', 'endedAt', 'id', 'jellyfinItemId', 'jellyfinSessionId', 'pausedDurationTicks', 'playMethod', 'startedAt', 'title', 'updatedAt', 'userId'] as const
  $columns = WatchSessionSchema.$columns
  @column()
  declare clientName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceName: string
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare jellyfinItemId: string
  @column()
  declare jellyfinSessionId: string | null
  @column()
  declare pausedDurationTicks: bigint | number
  @column()
  declare playMethod: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
}
